config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  resources :categories, only: [:index, :create, :update, :destroy]
  resources :income_and_expenditures
  root 'income_and_expenditures#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/income_and_expenditure.rb
class IncomeAndExpenditure < ApplicationRecord
  belongs_to :user
  belongs_to :category

  enum is_income_and_expenditure: { expenditure: false, income: true }

  validates :name, presence: true
  validates :price, presence: true

  scope :recent, -> { order(updated_at: :desc) }

  def self.income_and_expenditure_chart_data(data)
    result = {}
    data.each do |datum|
      result.store(datum.category.name, datum.price)
    end
    return result
  end
end

app/controllers/income_and_expenditures_controller.rb
class IncomeAndExpendituresController < ApplicationController
  def index
    @incomes = current_user.income_and_expenditures.income.recent
    @expenditures = current_user.income_and_expenditures.expenditure.recent
    @income_chart = IncomeAndExpenditure.income_and_expenditure_chart_data(@incomes)
    @expenditure_chart = IncomeAndExpenditure.income_and_expenditure_chart_data(@expenditures)
  end

  def show
  end

  def new
    @income_and_expenditure = IncomeAndExpenditure.new
    @categories = current_user.categories
  end

  def create
    @income_and_expenditure = IncomeAndExpenditure.new(income_and_expenditures_params)
    if @income_and_expenditure.save
      redirect_to income_and_expenditures_path, flash: { income_and_expenditures_notice: "収支登録が完了しました" }
    else
      @categories = current_user.categories
      render "new", collection: @categories
    end
  end

  def edit
    @income_and_expenditure = current_user.income_and_expenditures.find(params[:id])
    @categories = current_user.categories
  end

  def update
    @income_and_expenditure = current_user.income_and_expenditures.find(params[:id])
    if @income_and_expenditure.update(income_and_expenditures_params)
      redirect_to income_and_expenditures_path, flash: { income_and_expenditures_notice: "収支の更新が完了しました" }
    else
      @categories = current_user.categories
      render "edit", collection: @categories
    end
  end

  def destroy
    income_and_expenditure = current_user.income_and_expenditures.find(params[:id])
    income_and_expenditure.destroy
    redirect_to income_and_expenditures_path, flash: { income_and_expenditures_notice: "収支の削除が完了しました" }
  end

  private

  def income_and_expenditures_params
    params.require(:income_and_expenditure).permit(:is_income_and_expenditure, :name, :price, :category_id).merge(user_id: current_user.id)
  end
end

app/helpers/income_and_expenditures_helper.rb
module IncomeAndExpendituresHelper
  def display_income_and_expenditure(is_income_and_expenditure)
    if is_income_and_expenditure == "expenditure"
      return "支出"
    elsif is_income_and_expenditure == "income"
      return "収入"
    end
  end
end

app/views/income_and_expenditures/_chart_table.html.erb
<div class="row mb-5">
  <div class="col-sm-12">
    <%= pie_chart chart %>
  </div>
</div>

<table class="table">
  <thead>
    <tr>
      <th scope="col">名前</th>
      <th scope="col">価格(円)</th>
      <th scope="col">カテゴリー</th>
      <th scope="col">収支区分</th>
      <th scope="col">作成日時</th>
      <th scope="col">更新日時</th>
      <th scope="col">各種ボタン</th>
    </tr>
  </thead>
  <tbody>
    <% objects.each do |object| %>
      <tr>
        <th scope="row"><%= object.name  %></th>
        <td><%= object.price.to_s(:delimited) %></td>
        <td><%= object.category.name %></td>
        <td><%= display_income_and_expenditure(object.is_income_and_expenditure) %></td>
        <td><%= object.created_at.strftime("%Y年%m月%d日 %H:%M:%S") %></td>
        <td><%= object.updated_at.strftime("%Y年%m月%d日 %H:%M:%S") %></td>
        <td>
          <%= link_to "編集", edit_income_and_expenditure_path(object), class: "btn btn-secondary" %>
          <%= link_to "削除", income_and_expenditure_path(object), method: :delete, class: "btn btn-danger", data: { confirm: "削除してもよろしいですか？" } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/income_and_expenditures/_form.html.erb
<%= form_with model: income_and_expenditure, class: "card card-body", local: true do |form| %>
  <%= render "layouts/error_messages", model: form.object %>
  <div class="row">
    <div class="col-sm-6">
      <%= form.select :is_income_and_expenditure, [["支出", "expenditure"],["収入", "income"]], {}, class: "form-control mb-4" %>
    </div>
    <div class="col-sm-6">
      <%= form.select :category_id, categories.map { |category| [category.name, category.id] }, {}, class: "form-control" %>
    </div>
  </div>
  <%= form.text_field :name, class: "form-control mb-4", placeholder: "内容を入力してください" %>
  <div class="row">
    <div class="col-sm-6">
      <%= form.number_field :price, class: "form-control mb-4" %>
    </div>
  </div>
  <div class="text-end">
    <%= form.submit submit_str, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/income_and_expenditures/edit.html.erb
<h1>収支編集</h1>

<div class="d-flex justify-content-between mb-3">
  <%= link_to "一覧画面に戻る", income_and_expenditures_path, class: "btn btn-secondary" %>
  <%= link_to "カテゴリー追加", categories_path, data: {"turbolinks" => false}, class: "btn btn-secondary" %>
</div>

<%= render "form", { income_and_expenditure: @income_and_expenditure, categories: @categories, submit_str: "更新" } %>

app/views/income_and_expenditures/index.html.erb
<h1>収支一覧</h1>

<% if flash[:income_and_expenditures_notice] %>
  <p class="alert alert-primary" role="alert"><%= flash[:income_and_expenditures_notice] %></p>
<% end %>

<div class="text-end mb-3">
  <%= link_to "新規作成へ", new_income_and_expenditure_path, class: "btn btn-secondary" %>
  <%= link_to "カテゴリー追加", categories_path, data: {"turbolinks" => false}, class: "btn btn-secondary" %>
</div>

<ul class="nav nav-pills nav-justified mb-5" id="pills-tab" role="tablist">
  <li class="nav-item" role="presentation">
    <a class="nav-link active" id="pills-income-tab" data-bs-toggle="pill" href="#pills-income" role="tab" aria-controls="pills-income" aria-selected="true">収入</a>
  </li>
  <li class="nav-item" role="presentation">
    <a class="nav-link" id="pills-expenditure-tab" data-bs-toggle="pill" href="#pills-expenditure" role="tab" aria-controls="pills-expenditure" aria-selected="false">支出</a>
  </li>
</ul>
<div class="tab-content" id="pills-tabContent">
  <div class="tab-pane fade show active" id="pills-income" role="tabpanel" aria-labelledby="pills-income-tab">
    <%= render "chart_table", { objects: @incomes, chart: @income_chart } %>
  </div>
  <div class="tab-pane fade" id="pills-expenditure" role="tabpanel" aria-labelledby="pills-expenditure-tab">
    <%= render "chart_table", { objects: @expenditures, chart: @expenditure_chart } %>
  </div>
</div>

app/views/income_and_expenditures/new.html.erb
<h1>収支登録</h1>

<div class="d-flex justify-content-between mb-3">
  <%= link_to "一覧画面に戻る", income_and_expenditures_path, class: "btn btn-secondary" %>
  <%= link_to "カテゴリー追加", categories_path, data: {"turbolinks" => false}, class: "btn btn-secondary" %>
</div>

<%= render "form", { income_and_expenditure: @income_and_expenditure, categories: @categories, submit_str: "追加" } %>