config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  resources :categories, only: [:index, :create, :update, :destroy]
  resources :income_and_expenditures
  root 'income_and_expenditures#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :income_and_expenditures
  belongs_to :user

  validates :name, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = current_user.categories
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path, flash: { category_notice: "カテゴリーの登録が完了しました" }
    else
      @categories = current_user.categories
      render "index", collection: @categories
    end
  end

  def update
    category = current_user.categories.find(params[:id])
    if category.update(category_params)
      redirect_to categories_path, flash: { category_notice: "カテゴリーの更新が完了しました" }
    else
      @categories = current_user.categories
      render "index", collection: @categories
    end
  end

  def destroy
    category = current_user.categories.find(params[:id])
    category.destroy
    redirect_to categories_path, flash: { category_notice: "カテゴリーの削除が完了しました" }
  end

  private

  def category_params
    params.require(:category).permit(:name).merge(user_id: current_user.id)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/index.html.erb
<h1>カテゴリー</h1>

<% if flash[:category_notice] %>
  <p class="alert alert-primary" role="alert"><%= flash[:category_notice] %></p>
<% end %>

<div class="text-end mb-3">
  <button type="button" class="btn btn-primary" id="newButton">新規作成</button>
</div>
<%= form_with model: @category, class: "card card-body mb-3 d-none", id: "newCategory", local: true do |form| %>
  <div class="row">
    <div class="col-sm-6">
      <%= form.text_field :name, class: "form-control", id: "newText", placeholder: "カテゴリー名を入力してください" %>
    </div>
    <div class="col-sm-6 text-end">
      <button type="button" class="btn btn-secondary me-3" id="newCancel">キャンセル</button>
      <%= form.submit "追加", class: "btn btn-primary", id: "newSubmit", disabled: true %>
    </div>
  </div>
<% end %>

<div class="card">
  <div class="card-header">
    <div class="row d-flex justify-content-between mb-3">
      <div class="col-sm-3">カテゴリー名</div>
      <div class="col-sm-3">作成日時</div>
      <div class="col-sm-3">更新日時</div>
      <div class="col-sm-3">各種ボタン</div>
    </div>
  </div>
  <div class="card-body">
    <% @categories.each_with_index do |category, index| %>
      <div class="row d-flex justify-content-between mb-3">
        <div class="col-sm-3"><%= category.name %></div>
        <div class="col-sm-3"><%= category.created_at.strftime("%Y年%m月%d日 %H:%M:%S") %></div>
        <div class="col-sm-3"><%= category.updated_at.strftime("%Y年%m月%d日 %H:%M:%S") %></div>
        <div class="col-sm-3">
          <button type="button" class="btn btn-secondary me-3" id="editButton<%= index + 1 %>">編集</button>
          <%= link_to "削除", category_path(category), method: :delete, class: "btn btn-danger", data: { confirm: "削除してもよろしいですか？" } %>
        </div>
      </div>
      <%= form_with model: category, class: "card card-body mb-3 d-none", id: "editCategory#{index + 1}", local: true do |form| %>
        <div class="row">
          <div class="col-sm-8">
            <%= form.text_field :name, class: "form-control", id: "editText#{index + 1}", value: category.name %>
          </div>
          <div class="col-sm-4 text-center">
            <button type="button" class="btn btn-secondary me-3" id="editCancel<%= index + 1 %>">キャンセル</button>
            <%= form.submit "更新", class: "btn btn-primary", id: "editSubmit#{index + 1}" %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>